[build]
builder = "NIXPACKS"

[deploy]
startCommand = "node silva.js"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[[mounts]]
source = "mega-md-data"
target = "/data"
